### ISSUE TITLE
👋 Today button cannot be clicked and does not work

### ISSUE THREAD

**Issue by 404KSG** [mlava/yesterday-tomorrow#3]
Hello, could you help me check why this extension does not work in my graph? The today button in the middle of this extension cannot be clicked, and the left and right buttons can be clicked. However, when it is on a non-DNP page, the left and right buttons cannot be clicked, and only the middle one can work.

I tried my other graphs and this extension is worl, but this one cannot be used and is not work. Could you help me check the problem?

https://roam-research-6a2c436dc9f6.intercom-attachments-3.com/i/o/1083496246/7ada3699f662b0e6ef4ebf3d/bandicam+2024-06-16+20-17-25-880.mp4?expires=1718542533&signature=7dacebcacb00ef166b8e314e764521e8e6e85e0ea238be0b81017ecc28771d46

![image](https://github.com/mlava/yesterday-tomorrow/assets/80526156/7c42e61f-7376-46a6-bf70-738b98540c56)

**Comment by mlava** [comment]
What ended up being the issue, if I may ask?

**Comment by 404KSG** [comment]
- The end result is hard to explain haha, when the date changes to June
   17th at 0 o'clock, it automatically clicks. Not on the 16th.
   - But I still have a problem, that is, after clicking on the
   breadcrumbs, if I click on yesterday or tomorrow, it will not work. like
   this:
   [image: image.png]


Mark Lavercombe ***@***.***> 于2024年6月17日周一 19:07写道：
